name: test

on:
  push:
    branches:
      - masterminds
    paths:
      - "*.go"
      - ".github/workflows/main.yml"
  pull_request:
    branches:
      - master
jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: "go.mod"
    - name: check contents table
      run: |
        go test ./...
